/*- Package Declaration ------------------------------------------------------*/
package ch.psi.wica.controlsystem.epics.monitor;

/*- Imported packages --------------------------------------------------------*/

import ch.psi.wica.controlsystem.epics.channel.EpicsChannelName;
import ch.psi.wica.controlsystem.epics.metadata.EpicsChannelMetadataRequest;
import ch.psi.wica.model.channel.WicaChannel;
import net.jcip.annotations.Immutable;
import org.apache.commons.lang3.Validate;

/*- Interface Declaration ----------------------------------------------------*/
/*- Class Declaration --------------------------------------------------------*/

@Immutable
public class EpicsChannelMonitorRequest
{

/*- Public attributes --------------------------------------------------------*/
/*- Private attributes -------------------------------------------------------*/

   private final EpicsChannelName epicsChannelName;
   private final WicaChannel publicationChannel;


/*- Main ---------------------------------------------------------------------*/
/*- Constructor --------------------------------------------------------------*/

   /**
    * Creates a new instance to request the monitoring of the specified Wica channel.
    *
    * @param wicaChannel the channel.
    */
   public EpicsChannelMonitorRequest( WicaChannel wicaChannel )
   {
      this( EpicsChannelName.of( Validate.notNull( wicaChannel ).getName().getControlSystemName() ), wicaChannel );
   }

   /**
    * Creates a new instance which requests the monitoring of the specified EPICS
    * channel name and publication on the specified Wica Channel.
    *
    * @param epicsChannelName the EPICS channel name.
    * @param publicationChannel the channel.
    */
   EpicsChannelMonitorRequest( EpicsChannelName epicsChannelName, WicaChannel publicationChannel )
   {
      this.epicsChannelName = Validate.notNull( epicsChannelName );
      this.publicationChannel = Validate.notNull( publicationChannel );
   }

/*- Class methods ------------------------------------------------------------*/
/*- Public methods -----------------------------------------------------------*/

   public EpicsChannelMetadataRequest getAsMetadataRequest()
   {
      return new EpicsChannelMetadataRequest( this.epicsChannelName, this.publicationChannel );
   }

   /**
    * Returns the EPICS channel name associated with this request.
    *
    * @return the channel name.
    */
   public EpicsChannelName getEpicsChannelName()
   {
      return epicsChannelName;
   }

   /**
    * Returns the Wica channel associated with this request.
    *
    * @return the Wica channel.
    */
   public WicaChannel getPublicationChannel()
   {
      return publicationChannel;
   }

   @Override
   public String toString()
   {
      return "Monitor<" + publicationChannel.getName() + '>';
   }

   // Note on class identity implementation
   //
   // The EpicsChannelMonitorService enforces the rule that it will not allow
   // multiple requests that are considered "the same".
   //
   // Requests are considered the same if they refer to the same EPICS channel
   // name operating on the same WicaChannel.
   //
   // The equals and hashcode implementations below were generated by IntelliJ
   // and give us what we need.

   @Override
   public boolean equals( Object o )
   {
      if ( this == o )
      {
         return true;
      }
      if ( o == null || getClass() != o.getClass() )
      {
         return false;
      }

      EpicsChannelMonitorRequest that = (EpicsChannelMonitorRequest) o;

      if ( !epicsChannelName.equals( that.epicsChannelName ) )
      {
         return false;
      }
      return publicationChannel.equals( that.publicationChannel );
   }

   @Override
   public int hashCode()
   {
      int result = epicsChannelName.hashCode();
      result = 31 * result + publicationChannel.hashCode();
      return result;
   }



/*- Private methods ----------------------------------------------------------*/
/*- Nested Classes -----------------------------------------------------------*/

}
