/*- Package Declaration ------------------------------------------------------*/
package ch.psi.wica.controlsystem.epics.metadata;

/*- Imported packages --------------------------------------------------------*/

import ch.psi.wica.controlsystem.epics.channel.EpicsChannelName;
import ch.psi.wica.model.channel.WicaChannel;
import net.jcip.annotations.Immutable;
import org.apache.commons.lang3.Validate;

/*- Interface Declaration ----------------------------------------------------*/
/*- Class Declaration --------------------------------------------------------*/

@Immutable
public class EpicsChannelMetadataRequest
{

/*- Public attributes --------------------------------------------------------*/
/*- Private attributes -------------------------------------------------------*/

   private final EpicsChannelName epicsChannelName;
   private final WicaChannel publicationChannel;


/*- Main ---------------------------------------------------------------------*/
/*- Constructor --------------------------------------------------------------*/

   /**
    *
    * @param wicaChannel
    */
   public EpicsChannelMetadataRequest( WicaChannel wicaChannel )
   {
      this( EpicsChannelName.of( Validate.notNull( wicaChannel.getName().getControlSystemName() ) ), wicaChannel );
   }

   /**
    *
    * @param epicsChannelName
    * @param publicationChannel
    */
   public EpicsChannelMetadataRequest( EpicsChannelName epicsChannelName, WicaChannel publicationChannel )
   {
      this.epicsChannelName = Validate.notNull( epicsChannelName );
      this.publicationChannel = Validate.notNull( publicationChannel );
   }

/*- Class methods ------------------------------------------------------------*/
/*- Public methods -----------------------------------------------------------*/

   public EpicsChannelName getEpicsChannelName()
   {
      return epicsChannelName;
   }

   public WicaChannel getPublicationChannel()
   {
      return publicationChannel;
   }

   @Override
   public String toString()
   {
      return "Metadata<" + publicationChannel.getName() + '>';
   }

   // Note on class identity implementation
   //
   // The EpicsChannelMetadataService enforces the rule that it will not allow
   // multiple requests that are considered "the same".
   //
   // Requests are considered the same if they refer to the same EPICS channel
   // name operating on the same WicaChannel.
   //
   // The equals and hashcode implementations below were generated by IntelliJ
   // and give us what we need.

   @Override
   public boolean equals( Object o )
   {
      if ( this == o )
      {
         return true;
      }
      if ( o == null || getClass() != o.getClass() )
      {
         return false;
      }

      EpicsChannelMetadataRequest that = (EpicsChannelMetadataRequest) o;

      if ( !epicsChannelName.equals( that.epicsChannelName ) )
      {
         return false;
      }
      return publicationChannel.equals( that.publicationChannel );
   }

   @Override
   public int hashCode()
   {
      int result = epicsChannelName.hashCode();
      result = 31 * result + publicationChannel.hashCode();
      return result;
   }


/*- Private methods ----------------------------------------------------------*/
/*- Nested Classes -----------------------------------------------------------*/

}
