/*- Package Declaration ------------------------------------------------------*/
package ch.psi.wica.controlsystem.epics.poller;

/*- Imported packages --------------------------------------------------------*/

import ch.psi.wica.controlsystem.epics.channel.EpicsChannelName;
import ch.psi.wica.controlsystem.epics.metadata.EpicsChannelMetadataRequest;
import ch.psi.wica.model.channel.WicaChannel;
import net.jcip.annotations.Immutable;
import org.apache.commons.lang3.Validate;

/*- Interface Declaration ----------------------------------------------------*/
/*- Class Declaration --------------------------------------------------------*/

@Immutable
public class EpicsChannelPollerRequest
{

/*- Public attributes --------------------------------------------------------*/
/*- Private attributes -------------------------------------------------------*/

   private final EpicsChannelName epicsChannelName;
   private final int pollingInterval;
   private final WicaChannel publicationChannel;


/*- Main ---------------------------------------------------------------------*/
/*- Constructor --------------------------------------------------------------*/

   public EpicsChannelPollerRequest( WicaChannel wicaChannel )
   {
      this( EpicsChannelName.of( Validate.notNull( wicaChannel.getName().getControlSystemName() ) ), wicaChannel.getProperties().getPollingIntervalInMillis(), wicaChannel );
   }

   EpicsChannelPollerRequest( EpicsChannelName epicsChannelName, int pollingIntervalInMillis, WicaChannel publicationChannel )
   {
      this.epicsChannelName = Validate.notNull( epicsChannelName );
      this.pollingInterval = pollingIntervalInMillis;
      this.publicationChannel = Validate.notNull( publicationChannel );
   }

/*- Class methods ------------------------------------------------------------*/
/*- Public methods -----------------------------------------------------------*/

   public EpicsChannelMetadataRequest getAsMetadataRequest()
   {
      return new EpicsChannelMetadataRequest( this.epicsChannelName, this.publicationChannel );
   }

   public EpicsChannelName getEpicsChannelName()
   {
      return epicsChannelName;
   }

   public int getPollingInterval()
   {
      return pollingInterval;
   }

   public WicaChannel getPublicationChannel()
   {
      return publicationChannel;
   }

   @Override
   public String toString()
   {
      return "Poller<" + publicationChannel.getName() + "," + pollingInterval + '>';
   }

   // Note on class identity implementation
   //
   // The EpicsChannelPollerService enforces the rule that it will not allow
   // multiple requests that are considered "the same".
   //
   // For polling channels requests are considered the same if they refer to
   // the same EPICS channel name operating at the same polling interval on
   // the same WicaChannel.
   //
   // The equals and hashcode implementations below were generated by IntelliJ
   // and give us what we need.

   @Override
   public boolean equals( Object o )
   {
      if ( this == o )
      {
         return true;
      }
      if ( o == null || getClass() != o.getClass() )
      {
         return false;
      }

      EpicsChannelPollerRequest that = (EpicsChannelPollerRequest) o;

      if ( pollingInterval != that.pollingInterval )
      {
         return false;
      }
      if ( !epicsChannelName.equals( that.epicsChannelName ) )
      {
         return false;
      }
      return publicationChannel.equals( that.publicationChannel );
   }

   @Override
   public int hashCode()
   {
      int result = epicsChannelName.hashCode();
      result = 31 * result + pollingInterval;
      result = 31 * result + publicationChannel.hashCode();
      return result;
   }



   /*- Private methods ----------------------------------------------------------*/
/*- Nested Classes -----------------------------------------------------------*/

}
